esphome:
  name: kuchnia-rgbww

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "M5iAEVjLPFSHcB9iXbve3cjARvry9n0Adshvgcf4+5Q="

ota:
  password: "968f8e65e13b8825755c19de115e3aaa"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kuchnia-Rgbww"
    password: "X6ll52yQaE1q"

captive_portal:
    
# MOJE RZECZY
button:
  - platform: shutdown
    name: "Kuchnia Sterownik RGBWW Shutdown"

light:
  - platform: rgbww
    name: kuchnia_rgbww
    id: kuchnia_rgbww
    red: kuchnia_r
    green: kuchnia_g
    blue: kuchnia_b
    cold_white: kuchnia_cw
    warm_white: kuchnia_ww

output:
  - platform: esp8266_pwm
    pin: D1
    id: kuchnia_r

  - platform: esp8266_pwm
    pin: D2
    id: kuchnia_g

  - platform: esp8266_pwm
    pin: D3
    id: kuchnia_b

  - platform: esp8266_pwm
    pin: D4
    id: kuchnia_cw

  - platform: esp8266_pwm
    pin: D8
    id: kuchnia_ww

globals:
  - id: dimming
    type: bool
    restore_value: no
    initial_value: 'true'

binary_sensor:
  - platform: gpio
    name: kuchnia_rgbww_mode
    id: kuchnia_rgbww_mode
    pin:
      number: D5
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_click:
      then:
        - if:
            condition:
              light.is_off: kuchnia_rgbww
            then:
              - lambda: |-
                  id(dimming) = true;
              - light.turn_on:
                  id: kuchnia_rgbww
                  color_mode: RGB_COLD_WARM_WHITE
                  brightness: 50% 
                  color_brightness: 0%
                  cold_white: 0%
                  warm_white: 100%
            else:
              - light.turn_off: kuchnia_rgbww
    on_press:
      then:
        - delay: 0.5s
        - if:
            condition: 
              binary_sensor.is_on: kuchnia_rgbww_mode
            then:
              - while:
                  condition:
                    binary_sensor.is_on: kuchnia_rgbww_mode
                  then:
                    - if:
                        condition: 
                            lambda: |-
                              return id(dimming);
                        then:
                                
                          - light.dim_relative:
                              id: kuchnia_rgbww
                              relative_brightness: 2%
                              transition_length: 0.1s
                          - delay: 0.1s
                        else:
                          - light.dim_relative:
                              id: kuchnia_rgbww
                              relative_brightness: -2%
                              transition_length: 0.1s
                          - delay: 0.1s               
              - lambda: |-
                  id(dimming) = !id(dimming);
