esphome:
  name: kuchnia-rgbww

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "M5iAEVjLPFSHcB9iXbve3cjARvry9n0Adshvgcf4+5Q="

ota:
  password: "968f8e65e13b8825755c19de115e3aaa"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kuchnia-Rgbww"
    password: "X6ll52yQaE1q"

captive_portal:
    
# MOJE RZECZY
light:
  - platform: rgbww
    name: kuchnia_rgbww
    id: kuchnia_rgbww
    red: kuchnia_r
    green: kuchnia_g
    blue: kuchnia_b
    cold_white: kuchnia_cw
    warm_white: kuchnia_ww
    cold_white_color_temperature: 5750 K
    warm_white_color_temperature: 3050 K

output:
  - platform: esp8266_pwm
    pin: D1
    id: kuchnia_r

  - platform: esp8266_pwm
    pin: D2
    id: kuchnia_g

  - platform: esp8266_pwm
    pin: D5
    id: kuchnia_b

  - platform: esp8266_pwm
    pin: D6
    id: kuchnia_cw

  - platform: esp8266_pwm
    pin: D7
    id: kuchnia_ww
