esphome:
  name: kurnik-pokoj-rgbww

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "hBf4lSSlA8f8LuC30pm1gqMKgFX4SHkoncfw8r01p/4="

ota:
  password: "55a78d41500a36fddcb9426dce7eb6d7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kurnik-Pokoj-Rgbww"
    password: "3Remp5d0ZTfM"

captive_portal:

# MOJE RZECZY
button:
  - platform: shutdown
    name: "Kurnik Pokój Sterownik RGBWW Shutdown"

light:
  - platform: rgbww
    name: kurnik_rgbww
    id: kurnik_rgbww
    red: kurnik_r
    green: kurnik_g
    blue: kurnik_b
    cold_white: kurnik_cw
    warm_white: kurnik_ww
  
  - platform: rgbww
    name: pokoj_1_rgbww
    id: pokoj_1_rgbww
    red: pokoj_1_r
    green: pokoj_1_g
    blue: pokoj_1_b
    cold_white: pokoj_1_cw
    warm_white: pokoj_1_ww
  
  - platform: rgbww
    name: pokoj_2_rgbww
    id: pokoj_2_rgbww
    red: pokoj_2_r
    green: pokoj_2_g
    blue: pokoj_2_b
    cold_white: pokoj_2_cw
    warm_white: pokoj_2_ww

output:
  - platform: ledc
    pin: GPIO32
    id: kurnik_r

  - platform: ledc
    pin: GPIO33
    id: kurnik_g

  - platform: ledc
    pin: GPIO25
    id: kurnik_b

  - platform: ledc
    pin: GPIO26
    id: kurnik_cw

  - platform: ledc
    pin: GPIO27
    id: kurnik_ww

  - platform: ledc
    pin: GPIO14
    id: pokoj_1_r

  - platform: ledc
    pin: GPIO12
    id: pokoj_1_g

  - platform: ledc
    pin: GPIO13
    id: pokoj_1_b

  - platform: ledc
    pin: GPIO23
    id: pokoj_1_cw

  - platform: ledc
    pin: GPIO22
    id: pokoj_1_ww

  - platform: ledc
    pin: GPIO21
    id: pokoj_2_r

  - platform: ledc
    pin: GPIO19
    id: pokoj_2_g

  - platform: ledc
    pin: GPIO18
    id: pokoj_2_b

  - platform: ledc
    pin: GPIO5
    id: pokoj_2_cw

  - platform: ledc
    pin: GPIO17
    id: pokoj_2_ww
    
globals:
  - id: dimming_kurnik
    type: bool
    restore_value: no
    initial_value: 'true'
  - id: dimming_pokoj_1
    type: bool
    restore_value: no
    initial_value: 'true'
  - id: dimming_pokoj_2
    type: bool
    restore_value: no
    initial_value: 'true'

binary_sensor:
  - platform: gpio
    name: kurnik_rgbww_mode
    id: kurnik_rgbww_mode
    pin:
      number: GPIO16
      mode:
        input: true
        pulldown: true
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_click:
      then:
        - if:
            condition:
              light.is_off: kurnik_rgbww
            then:
              - lambda: |-
                  id(dimming_kurnik) = true;
              - light.turn_on:
                  id: kurnik_rgbww
                  color_mode: RGB_COLD_WARM_WHITE
                  brightness: 50% 
                  color_brightness: 0%
                  cold_white: 0%
                  warm_white: 100%
            else:
              - light.turn_off: kurnik_rgbww
    on_press:
      then:
        - delay: 0.5s
        - if:
            condition: 
              binary_sensor.is_on: kurnik_rgbww_mode
            then:
              - while:
                  condition:
                    binary_sensor.is_on: kurnik_rgbww_mode
                  then:
                    - if:
                        condition: 
                            lambda: |-
                              return id(dimming_kurnik);
                        then:
                                
                          - light.dim_relative:
                              id: kurnik_rgbww
                              relative_brightness: 2%
                              transition_length: 0.1s
                          - delay: 0.1s
                        else:
                          - light.dim_relative:
                              id: kurnik_rgbww
                              relative_brightness: -2%
                              transition_length: 0.1s
                          - delay: 0.1s               
              - lambda: |-
                  id(dimming_kurnik) = !id(dimming_kurnik);

  - platform: gpio
    name: pokoj_1_rgbww_mode
    id: pokoj_1_rgbww_mode
    pin:
      number: GPIO4
      mode:
        input: true
        pulldown: true
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_click:
      then:
        - if:
            condition:
              light.is_off: pokoj_1_rgbww
            then:
              - lambda: |-
                  id(dimming_pokoj_1) = true;
              - light.turn_on:
                  id: pokoj_1_rgbww
                  color_mode: RGB_COLD_WARM_WHITE
                  brightness: 50% 
                  color_brightness: 0%
                  cold_white: 0%
                  warm_white: 100%
            else:
              - light.turn_off: pokoj_1_rgbww
    on_press:
      then:
        - delay: 0.5s
        - if:
            condition: 
              binary_sensor.is_on: pokoj_1_rgbww_mode
            then:
              - while:
                  condition:
                    binary_sensor.is_on: pokoj_1_rgbww_mode
                  then:
                    - if:
                        condition: 
                            lambda: |-
                              return id(dimming_pokoj_1);
                        then:
                                
                          - light.dim_relative:
                              id: pokoj_1_rgbww
                              relative_brightness: 2%
                              transition_length: 0.1s
                          - delay: 0.1s
                        else:
                          - light.dim_relative:
                              id: pokoj_1_rgbww
                              relative_brightness: -2%
                              transition_length: 0.1s
                          - delay: 0.1s               
              - lambda: |-
                  id(dimming_pokoj_1) = !id(dimming_pokoj_1);

  - platform: gpio
    name: pokoj_2_rgbww_mode
    id: pokoj_2_rgbww_mode
    pin:
      number: GPIO2
      mode:
        input: true
        pulldown: true
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_click:
      then:
        - if:
            condition:
              light.is_off: pokoj_2_rgbww
            then:
              - lambda: |-
                  id(dimming_pokoj_2) = true;
              - light.turn_on:
                  id: pokoj_2_rgbww
                  color_mode: RGB_COLD_WARM_WHITE
                  brightness: 50% 
                  color_brightness: 0%
                  cold_white: 0%
                  warm_white: 100%
            else:
              - light.turn_off: pokoj_2_rgbww
    on_press:
      then:
        - delay: 0.5s
        - if:
            condition: 
              binary_sensor.is_on: pokoj_2_rgbww_mode
            then:
              - while:
                  condition:
                    binary_sensor.is_on: pokoj_2_rgbww_mode
                  then:
                    - if:
                        condition: 
                            lambda: |-
                              return id(dimming_pokoj_2);
                        then:
                                
                          - light.dim_relative:
                              id: pokoj_2_rgbww
                              relative_brightness: 2%
                              transition_length: 0.1s
                          - delay: 0.1s
                        else:
                          - light.dim_relative:
                              id: pokoj_2_rgbww
                              relative_brightness: -2%
                              transition_length: 0.1s
                          - delay: 0.1s               
              - lambda: |-
                  id(dimming_pokoj_2) = !id(dimming_pokoj_2);
