esphome:
  name: led-common

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "2bhz8/S7mC/DzXQO1AdYhUw4S8jM1uG0qi+fAJZifw4="

ota:
  password: "83f5a509dd5d1036ebee56df94a76b38"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led-Common Fallback Hotspot"
    password: "CEpilzkFBoH7"

captive_portal:


### MOJE ###

output:
  - platform: esp8266_pwm
    pin: GPIO15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: GPIO13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 1000 Hz
    id: pwm_cw
  - platform: esp8266_pwm
    pin: GPIO04
    frequency: 1000 Hz
    id: pwm_ww

light:
  - platform: rgbww
    id: common_rgbww
    name: "LED Common"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    warm_white: pwm_ww
    cold_white: pwm_cw

globals:
  - id: dimming
    type: bool
    restore_value: no
    initial_value: 'true'

binary_sensor:
  - platform: gpio
    name: "Przełącznik Światła Common"
    id: common_rgbww_mode
    pin:
      number: GPIO3
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_click:
      then:
        - if:
            condition:
              light.is_off: common_rgbww
            then:
              - lambda: |-
                  id(dimming) = true;
              - light.turn_on:
                  id: common_rgbww
                  color_mode: RGB_COLD_WARM_WHITE
                  brightness: 50% 
                  color_brightness: 0%
                  cold_white: 0%
                  warm_white: 100%
            else:
              - light.turn_off: common_rgbww
    on_press:
      then:
        - delay: 0.5s
        - if:
            condition: 
              binary_sensor.is_on: common_rgbww_mode
            then:
              - while:
                  condition:
                    binary_sensor.is_on: common_rgbww_mode
                  then:
                    - if:
                        condition: 
                            lambda: |-
                              return id(dimming);
                        then:
                                
                          - light.dim_relative:
                              id: common_rgbww
                              relative_brightness: 2%
                              transition_length: 0.1s
                          - delay: 0.1s
                        else:
                          - light.dim_relative:
                              id: common_rgbww
                              relative_brightness: -2%
                              transition_length: 0.1s
                          - delay: 0.1s               
              - lambda: |-
                  id(dimming) = !id(dimming);

### MOJE ###